# Generated by Django 4.2.27 on 2025-12-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileresource',
            new_name='catalog_fil_file_na_e4ae31_idx',
            old_name='catalog_fil_file_na_b4e4a1_idx',
        ),
        migrations.RenameIndex(
            model_name='fileresource',
            new_name='catalog_fil_extensi_b1401c_idx',
            old_name='catalog_fil_extensi_5b6c41_idx',
        ),
        migrations.RenameIndex(
            model_name='fileresource',
            new_name='catalog_fil_relativ_02c87d_idx',
            old_name='catalog_fil_relativ_ff3759_idx',
        ),
    ]
