# Generated by Django 6.0.2 on 2026-05-10 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_catalog_fil_file_na_b4e4a1_idx_catalog_fil_file_na_e4ae31_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=2048)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error')], default='synced', max_length=20)),
                ('availability', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing')], default='present', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_id', 'relative_path'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('root_path', models.CharField(max_length=2048)),
            ],
            options={
                'ordering': ['device_id', 'root_path'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='machine_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='os_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='device',
            name='platform_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='scanner_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('machine_uid__isnull', False), models.Q(('machine_uid', ''), _negated=True)), fields=('machine_uid',), name='catalog_device_machine_uid_unique_nonnull'),
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='catalog.project'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='materials', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_locations', to='catalog.device'),
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='catalog.material'),
        ),
        migrations.AddField(
            model_name='storagelocation',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='catalog.device'),
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_locations', to='catalog.storagelocation'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['file_name'], name='catalog_mat_file_na_2dd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['extension'], name='catalog_mat_extensi_b4bb3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagelocation',
            constraint=models.UniqueConstraint(fields=('device', 'root_path'), name='catalog_storage_device_root_unique'),
        ),
        migrations.AddIndex(
            model_name='materiallocation',
            index=models.Index(fields=['relative_path'], name='catalog_mat_relativ_80b484_idx'),
        ),
        migrations.AddIndex(
            model_name='materiallocation',
            index=models.Index(fields=['availability'], name='catalog_mat_availab_3ae628_idx'),
        ),
        migrations.AddConstraint(
            model_name='materiallocation',
            constraint=models.UniqueConstraint(fields=('device', 'storage_location', 'relative_path'), name='catalog_materialloc_unique_path'),
        ),
    ]
