# Generated by Django 4.2.30 on 2026-05-10 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_material_materiallocation_storagelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_kind',
            field=models.CharField(choices=[('generic', 'Generic catalog entry'), ('literature_list', 'Literature list'), ('bibliography', 'Bibliography'), ('reading_list', 'Reading list'), ('article_collection', 'Article collection'), ('research_material', 'Research material')], db_index=True, default='generic', max_length=32),
        ),
        migrations.CreateModel(
            name='LinkedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('book', 'Book'), ('article', 'Article'), ('doi', 'DOI'), ('arxiv', 'arXiv'), ('url', 'URL'), ('github', 'GitHub'), ('local_file', 'Local file'), ('local_folder', 'Local folder'), ('note', 'Note'), ('other', 'Other')], default='url', max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('url', models.CharField(blank=True, help_text='URL, DOI, arXiv id, or other identifier', max_length=2048)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_materials', to='catalog.fileresource')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_resources', to='catalog.material')),
            ],
            options={
                'ordering': ['material_id', 'created_at'],
                'indexes': [models.Index(fields=['title'], name='catalog_lin_title_72ce8c_idx'), models.Index(fields=['url'], name='catalog_lin_url_e55abf_idx'), models.Index(fields=['resource_type'], name='catalog_lin_resourc_86a589_idx')],
            },
        ),
    ]
