# Generated by Django 4.2.30 on 2026-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_material_kind_linkedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedresource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='linked_resource_links', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.CharField(blank=True, db_index=True, help_text='Тема или направление (удобно для списков литературы)', max_length=512, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='materiallocation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='material_location_paths', to='catalog.tag'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('PC', 'ПК'), ('Laptop', 'Ноутбук'), ('ExternalHDD', 'Внешний HDD/SSD'), ('USB', 'USB-накопитель'), ('Other', 'Другое')], default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='linkedresource',
            name='resource_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('book', 'Книга'), ('article', 'Статья'), ('doi', 'DOI'), ('arxiv', 'arXiv'), ('url', 'Ссылка (URL)'), ('github', 'GitHub'), ('local_file', 'Локальный файл'), ('local_folder', 'Локальная папка'), ('note', 'Заметка'), ('other', 'Другое')], default='url', max_length=32),
        ),
        migrations.AlterField(
            model_name='linkedresource',
            name='url',
            field=models.CharField(blank=True, help_text='URL, DOI, идентификатор arXiv или другой текст', max_length=2048),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_kind',
            field=models.CharField(choices=[('generic', 'Обычная запись каталога'), ('literature_list', 'Список литературы'), ('bibliography', 'Библиография'), ('reading_list', 'Список для чтения'), ('article_collection', 'Подборка статей'), ('research_material', 'Исследовательские материалы')], db_index=True, default='generic', max_length=32),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='availability',
            field=models.CharField(choices=[('present', 'Есть'), ('missing', 'Отсутствует')], default='present', max_length=20),
        ),
        migrations.AlterField(
            model_name='materiallocation',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('synced', 'Синхронизировано'), ('error', 'Ошибка')], default='synced', max_length=20),
        ),
    ]
