# Generated by Django 4.2.30 on 2026-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_material_topic_and_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='source_path',
            field=models.CharField(blank=True, help_text='Откуда взят файл (часто нужно ввести вручную: браузер не отдаёт полный путь к диску).', max_length=2048, verbose_name='Локальный путь'),
        ),
    ]
