# Generated by Django 4.2.30 on 2026-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_material_kind_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialkind',
            name='code',
            field=models.SlugField(help_text='Латиница и дефис; для ссылок (?kind=…) и API. Лучше не менять после создания.', max_length=32, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='materialkind',
            name='is_literature',
            field=models.BooleanField(default=False, help_text='Материалы этого типа попадают в поиск литературы и в общий список по умолчанию.', verbose_name='Раздел «литература»'),
        ),
        migrations.AlterField(
            model_name='materialkind',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='materialkind',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
