# Generated by Django 4.2.30 on 2026-05-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_materialkind_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResourceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=2048)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_resource_locations', to='catalog.device')),
                ('file_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk_locations', to='catalog.fileresource')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_resource_locations', to='catalog.storagelocation')),
            ],
            options={
                'ordering': ['device_id', 'relative_path'],
            },
        ),
        migrations.AddConstraint(
            model_name='fileresourcelocation',
            constraint=models.UniqueConstraint(fields=('file_resource', 'device', 'storage_location', 'relative_path'), name='catalog_fileresloc_unique_path'),
        ),
    ]
