# Generated by Django 4.2.30 on 2026-05-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_fileresource_disk_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresourcelocation',
            name='mtime_fs',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменён на диске'),
        ),
        migrations.AddField(
            model_name='fileresourcelocation',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='Размер копии на диске на момент сканирования', null=True, verbose_name='Размер (байт)'),
        ),
    ]
