# Generated by Django 4.2.30 on 2026-05-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_fileresourcelocation_size_mtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='scan_import_pending',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
