# Generated by Django 4.2.30 on 2026-05-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_material_scan_import_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='scan_inbox_ignored',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
